apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lore-ui
  namespace: lore-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: LORE_UI_HOSTNAME
spec:
  ingressClassName: nginx-ingress
  tls:
    - hosts:
        - LORE_UI_HOSTNAME
      secretName: lore-ui-tls
  rules:
    - host: LORE_UI_HOSTNAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lore-ui
                port:
                  number: 3000
