/**
 * LoreTask watcher job.
 *
 * Polls LoreTask custom resources for completed (Succeeded / Failed) CRs.
 * On success, creates a PR from the branch the ephemeral Job pushed.
 * On failure, updates the pipeline task with the error.
 * Cleans up old CRs after 1 hour.
 */

import { KubeConfig, CustomObjectsApi, CoreV1Api } from "@kubernetes/client-node";
import { platform } from "../platform.js";
import { query } from "../db.js";

// ── Helpers ─────────────────────────────────────────────────────────

async function shouldAutoReview(repo: string): Promise<boolean> {
  const rows = await query<{ settings: any }>(
    `SELECT settings FROM lore.repos WHERE full_name = $1`, [repo],
  );
  return rows[0]?.settings?.auto_review === true;
}

async function getIssueNumber(taskId: string): Promise<{ issue_number: number | null; target_repo: string }> {
  const rows = await query<{ issue_number: number | null; target_repo: string }>(
    `SELECT issue_number, target_repo FROM pipeline.tasks WHERE id = $1`,
    [taskId],
  );
  return rows[0] || { issue_number: null, target_repo: "" };
}

async function linkPrToIssue(repo: string, issueNumber: number | null, prUrl: string): Promise<void> {
  if (!issueNumber) return;
  try {
    await platform().commentOnIssue(repo, issueNumber, `PR created: ${prUrl}`);
    await platform().closeIssue(repo, issueNumber, "completed");
  } catch { /* best effort */ }
}

async function commentFailureOnIssue(repo: string, issueNumber: number | null, reason: string): Promise<void> {
  if (!issueNumber) return;
  try {
    await platform().commentOnIssue(repo, issueNumber, `Task failed: \`${reason}\``);
    await platform().addIssueLabel(repo, issueNumber, "lore-failed");
  } catch { /* best effort */ }
}

const GROUP = "lore.re-cinq.com";
const VERSION = "v1alpha1";
const PLURAL = "loretasks";

export async function watchLoreTasks(): Promise<void> {
  const kc = new KubeConfig();
  kc.loadFromCluster();
  const k8sApi = kc.makeApiClient(CustomObjectsApi);
  const namespace = process.env.NAMESPACE || "lore-agent";

  const result = await k8sApi.listNamespacedCustomObject({
    group: GROUP,
    version: VERSION,
    namespace,
    plural: PLURAL,
  });
  const items = (result as any).items || [];

  for (const lt of items) {
    const phase = lt.status?.phase;
    const taskId = lt.spec?.taskId;
    if (!taskId) continue;

    // Logs are now stored in GCS by the controller — no DB persistence needed

    // Skip already-processed tasks (DB-level guard against re-entry)
    if (phase === "Succeeded" || phase === "Failed") {
      const dbRows = await query<{ status: string }>(
        `SELECT status FROM pipeline.tasks WHERE id = $1`, [taskId],
      );
      const dbStatus = dbRows[0]?.status;
      if (dbStatus && !['running', 'queued'].includes(dbStatus)) {
        continue; // Already processed in a previous cycle
      }
    }

    if (phase === "Succeeded" && !lt.status?.prUrl && lt.spec?.taskType !== "review") {
      // Skip PR creation for tasks that produced no changes (e.g. general/research tasks)
      if (lt.status?.changedFiles === 0) {
        try {
          let { issue_number, target_repo } = await getIssueNumber(taskId);
          if (!target_repo) target_repo = lt.spec.targetRepo;

          const logUrl = `gs://${process.env.LORE_LOG_BUCKET || "lore-task-logs"}/${lt.spec.targetRepo}/${taskId}/output.log`;
          const output = lt.status?.output || "";

          // Create a GitHub issue with the result as the body (general tasks skip upfront issue creation)
          if (!issue_number) {
            try {
              const body = output
                ? `## ${lt.spec.taskType}\n\n${lt.spec.description}\n\n---\n\n${output.length > 60000 ? output.slice(-60000) + "\n\n…(truncated)" : output}\n\n---\n*Generated by Lore agent task \`${taskId}\`.*`
                : `## ${lt.spec.taskType}\n\n${lt.spec.description}\n\nTask completed (no output). See [logs](${logUrl}).`;
              const issue = await platform().createIssue(
                target_repo,
                `[lore] ${lt.spec.taskType}: ${lt.spec.description.substring(0, 80)}`,
                body,
                ["lore-managed", lt.spec.taskType],
              );
              issue_number = issue.number;
              await query(
                `UPDATE pipeline.tasks SET issue_number = $1, issue_url = $2 WHERE id = $3`,
                [issue.number, issue.url, taskId],
              );
            } catch { /* best effort */ }
          } else {
            // Issue already exists (e.g. webhook-dispatched) — post result as comment
            const body = output
              ? `## Result\n\n${output.length > 60000 ? output.slice(-60000) + "\n\n…(truncated)" : output}`
              : "Task completed (no code changes). See logs for full output.";
            await platform().commentOnIssue(target_repo, issue_number, body).catch(() => {});
          }

          // Don't close the issue — it's the deliverable for general tasks.
          // User may want to read the result and comment with follow-ups.

          await query(
            `UPDATE pipeline.tasks SET status = 'completed', log_url = $1, updated_at = now() WHERE id = $2`,
            [logUrl, taskId],
          );
          await query(
            `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'running', 'completed', $2)`,
            [taskId, JSON.stringify({ no_changes: true, issue_number })],
          );
          // Mark the LoreTask CR as handled so the watcher doesn't re-process it
          try {
            const current = await k8sApi.getNamespacedCustomObjectStatus({
              group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
            }) as any;
            await k8sApi.replaceNamespacedCustomObjectStatus({
              group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
              body: { ...current, status: { ...current.status, prUrl: 'no-changes', issueNumber: issue_number } },
            });
          } catch { /* best effort — CR may already be cleaned up */ }

          console.log(`[loretask-watcher] Task ${taskId} completed → issue #${issue_number || "none"}`);
        } catch (err: any) {
          console.error(`[loretask-watcher] Failed to complete no-change task ${taskId}: ${err.message}`);
        }
        continue;
      }

      // Create PR from the pushed branch (skip review tasks — they don't push code)
      try {
        const { issue_number, target_repo } = await getIssueNumber(taskId);
        const issueRef = issue_number ? `\n\nRefs #${issue_number}` : "";

        const pr = await platform().createPR(
          lt.spec.targetRepo,
          lt.spec.branch,
          `lore: ${lt.spec.taskType} — ${lt.spec.branch.split("/").pop()}`,
          `## ${lt.spec.taskType}\n\n${lt.spec.description}\n\n**Execution mode:** Claude Code (ephemeral Job)\n**Changed files:** ${lt.status.changedFiles || "unknown"}\n\nGenerated by Lore agent task \`${taskId}\`.${issueRef}`,
        );

        // Update pipeline.tasks
        await query(
          `UPDATE pipeline.tasks SET status = 'pr-created', pr_url = $1, pr_number = $2, target_branch = $3, updated_at = now() WHERE id = $4`,
          [pr.url, pr.number, lt.spec.branch, taskId],
        );

        // After updating pipeline.tasks with pr_url, also set log_url
        const logUrl = `gs://${process.env.LORE_LOG_BUCKET || "lore-task-logs"}/${lt.spec.targetRepo}/${taskId}/output.log`;
        await query(
          `UPDATE pipeline.tasks SET log_url = $1 WHERE id = $2`,
          [logUrl, taskId],
        );

        await query(
          `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'running', 'pr-created', $2)`,
          [taskId, JSON.stringify({ pr_url: pr.url })],
        );

        // Link PR to GitHub Issue and close it
        await linkPrToIssue(target_repo, issue_number, pr.url);

        // Update LoreTask status with PR URL
        const current = await k8sApi.getNamespacedCustomObjectStatus({
          group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
        }) as any;
        await k8sApi.replaceNamespacedCustomObjectStatus({
          group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
          body: { ...current, status: { ...current.status, prUrl: pr.url, prNumber: pr.number } },
        });

        console.log(`[loretask-watcher] Task ${taskId} → PR ${pr.url}`);

        // Trigger auto-review if enabled for this repo
        if (await shouldAutoReview(lt.spec.targetRepo)) {
          const reviewTaskResult = await query<{ id: string }>(
            `INSERT INTO pipeline.tasks (description, task_type, target_repo, created_by, context_bundle)
             VALUES ($1, $2, $3, $4, $5) RETURNING id`,
            [
              `Review PR #${pr.number} on ${lt.spec.targetRepo}`,
              'review',
              lt.spec.targetRepo,
              'loretask-watcher',
              JSON.stringify({ pr_number: pr.number, branch: lt.spec.branch, parent_task_id: taskId }),
            ],
          );
          const reviewTaskId = reviewTaskResult[0].id;

          // Create review LoreTask CR
          const reviewCRName = `loretask-${reviewTaskId.substring(0, 8)}`;
          await k8sApi.createNamespacedCustomObject({
            group: GROUP, version: VERSION, namespace, plural: PLURAL,
            body: {
              apiVersion: `${GROUP}/${VERSION}`,
              kind: "LoreTask",
              metadata: {
                name: reviewCRName,
                namespace,
                labels: {
                  "lore.re-cinq.com/task-id": reviewTaskId,
                  "lore.re-cinq.com/task-type": "review",
                },
              },
              spec: {
                taskId: reviewTaskId,
                taskType: "review",
                description: `Review PR #${pr.number} on ${lt.spec.targetRepo}`,
                prompt: `Review PR #${pr.number} on this branch. Read the spec in specs/ for the feature requirements. Check all changes against CLAUDE.md conventions and ADRs in adrs/. Post specific review comments on the PR using 'gh pr review'. Then output exactly one of:\n- REVIEW_RESULT:APPROVED\n- REVIEW_RESULT:CHANGES_REQUESTED:<specific actionable feedback>`,
                targetRepo: lt.spec.targetRepo,
                branch: lt.spec.branch,
                prNumber: pr.number,
                model: "claude-sonnet-4-6",
                timeoutMinutes: 10,
              },
            },
          });

          // Update implementation task to review status
          await query(
            `UPDATE pipeline.tasks SET status = 'review', updated_at = now() WHERE id = $1`,
            [taskId],
          );
          await query(
            `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'pr-created', 'review', $2)`,
            [taskId, JSON.stringify({ review_task_id: reviewTaskId, auto_review: true })],
          );

          console.log(`[loretask-watcher] Auto-review: created review task ${reviewTaskId} for PR #${pr.number}`);
        }
      } catch (err: any) {
        console.error(`[loretask-watcher] Failed to create PR for ${taskId}: ${err.message}`);
      }
    }

    if (phase === "Failed" && lt.status?.failureReason) {
      // Update pipeline.tasks with failure
      const rows = await query<{ status: string; issue_number: number | null; target_repo: string }>(
        `SELECT status, issue_number, target_repo FROM pipeline.tasks WHERE id = $1`, [taskId],
      );
      if (rows[0]?.status === "running") {
        await query(
          `UPDATE pipeline.tasks SET status = 'failed', failure_reason = $1, updated_at = now() WHERE id = $2`,
          [lt.status.failureReason, taskId],
        );

        // Set log_url for failed tasks so logs are still accessible
        const logUrl = `gs://${process.env.LORE_LOG_BUCKET || "lore-task-logs"}/${lt.spec.targetRepo}/${taskId}/output.log`;
        await query(
          `UPDATE pipeline.tasks SET log_url = $1 WHERE id = $2`,
          [logUrl, taskId],
        );

        await query(
          `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, 'running', 'failed', $2)`,
          [taskId, JSON.stringify({ error: lt.status.failureReason })],
        );
        await commentFailureOnIssue(rows[0].target_repo, rows[0].issue_number, lt.status.failureReason);

        // Capture failure as an episode for org-wide learning
        const failureContent = `Task failed on ${lt.spec.targetRepo}: ${lt.spec.taskType}\n\nDescription: ${lt.spec.description}\n\nFailure: ${lt.status.failureReason}\n\nOutput:\n${(lt.status?.output || '').slice(-2000)}`;
        const failureHash = require('node:crypto').createHash('sha256').update(failureContent).digest('hex');
        await query(
          `INSERT INTO memory.episodes (agent_id, content, content_hash, source, ref)
           VALUES ($1, $2, $3, 'ci', $4)
           ON CONFLICT (agent_id, content_hash) DO NOTHING`,
          ['loretask-watcher', failureContent, failureHash, `${lt.spec.targetRepo}/${taskId}`],
        ).catch(() => {});

        console.log(`[loretask-watcher] Task ${taskId} failed: ${lt.status.failureReason}`);
      }
    }

    // Handle completed review tasks (only if this review task hasn't been processed yet)
    if (phase === "Succeeded" && lt.spec.taskType === "review" && lt.status?.reviewResult) {
      // Skip if this review task is already in a terminal state in the DB
      const reviewTaskRow = (await query<{ status: string }>(`SELECT status FROM pipeline.tasks WHERE id = $1`, [taskId]))[0];
      if (reviewTaskRow && reviewTaskRow.status !== "running") {
        continue; // Already processed
      }
      const contextBundle = (await query<{ context_bundle: any }>(
        `SELECT context_bundle FROM pipeline.tasks WHERE id = $1`, [taskId],
      ))[0]?.context_bundle;
      const parentTaskId: string | undefined =
        lt.status?.parentTaskId || contextBundle?.parent_task_id;

      if (!parentTaskId) {
        console.log(`[loretask-watcher] Review ${taskId} has no parent task, skipping`);
        continue;
      }

      if (lt.status.reviewResult === "approved") {
        await query(
          `UPDATE pipeline.tasks SET status = 'completed', updated_at = now() WHERE id = $1`,
          [parentTaskId],
        );
        await query(
          `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, $2, $3, $4)`,
          [parentTaskId, 'review', 'completed', JSON.stringify({ review_result: 'approved', review_task_id: taskId })],
        );
        // Comment on issue
        const { issue_number, target_repo } = await getIssueNumber(parentTaskId);
        if (issue_number) {
          await platform().commentOnIssue(target_repo, issue_number, "Agent review: **approved**. PR is ready for human merge.").catch(() => {});
        }
        // Mark the review task itself as completed
        await query(`UPDATE pipeline.tasks SET status = 'completed', updated_at = now() WHERE id = $1`, [taskId]);
        console.log(`[loretask-watcher] Review approved for parent task ${parentTaskId}`);
      } else {
        // Changes requested — check iteration count
        const parentRows = await query<{
          review_iteration: number;
          target_repo: string;
          target_branch: string;
          description: string;
          issue_number: number | null;
        }>(
          `SELECT review_iteration, target_repo, target_branch, description, issue_number FROM pipeline.tasks WHERE id = $1`,
          [parentTaskId],
        );
        const parent = parentRows[0];
        if (!parent) continue;

        const iteration = (Number(parent.review_iteration) || 0) + 1;
        await query(`UPDATE pipeline.tasks SET review_iteration = $1, updated_at = now() WHERE id = $2`, [iteration, parentTaskId]);

        if (iteration >= 2) {
          // Escalate to human
          await query(
            `UPDATE pipeline.tasks SET status = 'review', updated_at = now() WHERE id = $1`,
            [parentTaskId],
          );
          await query(
            `INSERT INTO pipeline.task_events (task_id, from_status, to_status, metadata) VALUES ($1, $2, $3, $4)`,
            [parentTaskId, 'review', 'review', JSON.stringify({ review_result: 'needs-human-review', iterations: iteration })],
          );
          if (parent.issue_number) {
            await platform().commentOnIssue(parent.target_repo, parent.issue_number, `Agent review: changes requested (iteration ${iteration}/2). Escalating to human review.`).catch(() => {});
            await platform().addIssueLabel(parent.target_repo, parent.issue_number, "needs-human-review").catch(() => {});
          }
          console.log(`[loretask-watcher] Review escalated to human for ${parentTaskId} (iteration ${iteration})`);
        } else {
          // Create new implementation task with feedback on the same branch
          const feedback = lt.status.output || "Review requested changes";
          const fixTaskResult = await query<{ id: string }>(
            `INSERT INTO pipeline.tasks (description, task_type, target_repo, created_by, context_bundle)
             VALUES ($1, $2, $3, $4, $5) RETURNING id`,
            [
              `Fix review feedback on PR: ${feedback.substring(0, 200)}`,
              'implementation',
              parent.target_repo,
              'review-loop',
              JSON.stringify({ branch: parent.target_branch, review_feedback: feedback, parent_task_id: parentTaskId }),
            ],
          );
          const fixTaskId = fixTaskResult[0].id;

          // Create implementation LoreTask CR on the same branch
          await k8sApi.createNamespacedCustomObject({
            group: GROUP, version: VERSION, namespace, plural: PLURAL,
            body: {
              apiVersion: `${GROUP}/${VERSION}`,
              kind: "LoreTask",
              metadata: {
                name: `loretask-${fixTaskId.substring(0, 8)}`,
                namespace,
                labels: { "lore.re-cinq.com/task-id": fixTaskId, "lore.re-cinq.com/task-type": "implementation" },
              },
              spec: {
                taskId: fixTaskId,
                taskType: "implementation",
                description: `Fix review feedback: ${feedback.substring(0, 200)}`,
                prompt: `Address the following review feedback on this branch. The PR already exists — push fixes to the same branch.\n\nFeedback:\n${feedback}`,
                targetRepo: parent.target_repo,
                branch: parent.target_branch || lt.spec.branch,
                model: "claude-sonnet-4-6",
                timeoutMinutes: 30,
              },
            },
          });

          if (parent.issue_number) {
            await platform().commentOnIssue(parent.target_repo, parent.issue_number, `Agent review: changes requested (iteration ${iteration}/2). Auto-fixing...`).catch(() => {});
          }
          console.log(`[loretask-watcher] Review changes requested, created fix task ${fixTaskId} (iteration ${iteration})`);
        }
      }
    }

    // Clean up old completed LoreTasks (> 1 hour old with PR, no changes, or failed)
    if ((phase === "Succeeded" && (lt.status?.prUrl || lt.status?.changedFiles === 0)) || (phase === "Failed")) {
      const completedAt = lt.status?.completedAt ? new Date(lt.status.completedAt) : null;
      if (completedAt && Date.now() - completedAt.getTime() > 60 * 60 * 1000) {
        const taskIdShort = taskId.substring(0, 8);
        try {
          await k8sApi.deleteNamespacedCustomObject({
            group: GROUP, version: VERSION, namespace, plural: PLURAL, name: lt.metadata.name,
          });
          console.log(`[loretask-watcher] Cleaned up LoreTask ${lt.metadata.name}`);
        } catch { /* best effort */ }
        // Clean up orphaned token secret
        try {
          const coreApi = kc.makeApiClient(CoreV1Api);
          await coreApi.deleteNamespacedSecret({ name: `loretask-github-token-${taskIdShort}`, namespace });
        } catch { /* already gone or never created */ }
      }
    }
  }
}

/**
 * Job wrapper for the scheduler. Returns a summary string.
 */
export async function loretaskWatcherJob(): Promise<string> {
  await watchLoreTasks();
  return "LoreTask watcher completed";
}
